meta-digi-dey: update dey-image-graphical for yocto 1.8
owl-video and gpu-viv-bin packages have been removed

Fix:

ERROR: Nothing RPROVIDES 'owl-video'
ERROR: Nothing RPROVIDES 'gpu-viv-bin-mx6q'
ERROR: Nothing RPROVIDES 'gpu-viv-g2d'

https://jira.digi.com/browse/DEL-1558

Signed-off-by: Javier Viguera <javier.viguera@digi.com>