amd-gpu-bin-mx51: rework package
To avoid conflicts between the two flavous (X11, framebuffer). Also fix
bitbake parsing error in the buildserver:

ERROR: Nothing PROVIDES 'virtual/libx11' (but
amd-gpu-x11-bin-mx51_11.09.01.bb DEPENDS on or otherwise requires it)

Signed-off-by: Javier Viguera <javier.viguera@digi.com>