morty migration: card-detect: fix build failure
Let Yocto use their own compilation flags instead of hard-coding the
compile command. This fixes:

ERROR: card-detect-1.0-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary

https://jira.digi.com/browse/DEL-3451

Signed-off-by: Javier Viguera <javier.viguera@digi.com>