crda: fix error related to multiline comment
With latest changes in bitbake (post-danny), crda recipe was giving
following error:

ERROR: There is a confusing multiline, partially commented expression

Signed-off-by: Javier Viguera <javier.viguera@digi.com>