trustfence: add 'expand' parameter to getVar calls
Starting with Yocto 2.1, the 'expand' parameter of 'getVar' function is
mandatory. See:

http://www.yoctoproject.org/docs/2.2.1/ref-manual/ref-manual.html#migration-2.1-expand-parameter-to-getvar-and-getvarflag-now-mandatory

This fixes build failures as:

Exception: TypeError: getVar() missing 1 required positional argument: 'expand'

https://jira.digi.com/browse/DEL-3834

Signed-off-by: Javier Viguera <javier.viguera@digi.com>