recipes-graphics: imx-gpu-viv: Update to new NXP BSP release imx-5.4.24-2.1.0.
This commit updates the imx-gpu-viv to the next version.

It includes the following improvments and fixes

* The work-around that moves .so for OpenCL, OpenVX, and Vulkan
  to the main packages triggers the QA Issue for dev-so:

    ERROR: imx-gpu-viv-1_6.4.0.p2.4-aarch64-r0 do_package_qa:
    QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so:
    libvulkan-imx path '/work/aarch64-mx8m-poky-linux/imx-gpu-viv/1_6.4.0.p2.4-aarch64-r0/packages-split/libvulkan-imx/usr/lib/libvulkan_VSI.so' [dev-so]

    Suppress the QA check.

* Add versions for OpenCL, OpenVX, and Vulkan.

Signed-off-by: Mike Engel <Mike.Engel@digi.com>