build.sh: fix random build failures in the buildserver
We have seen lately random build failures in the buildserver due to
missing QT5 base libraries that are needed when building some other
QT5 packages.

Examples:

Compiling qtdeclarative:

error: cannot open .../tmp/work/cortexa9hf-vfp-neon-mx6qdl-dey-linux-gnueabi/qtbase/5.5.1+gitAUTOINC+5afc431323-r0/build/lib/libQt5Core.so: No such file or directory

error: cannot open .../tmp/work/cortexa9hf-vfp-neon-mx6qdl-dey-linux-gnueabi/qtbase/5.5.1+gitAUTOINC+5afc431323-r0/build/lib/libQt5Network.so: No such file or directory

error: cannot open .../tmp/work/cortexa9hf-vfp-neon-mx6qdl-dey-linux-gnueabi/qtbase/5.5.1+gitAUTOINC+5afc431323-r0/build/lib/libQt5Widgets.so: No such file or directory

The problem here is that 'qtdeclarative' is trying to get the needed
libraries from the 'qtbase' temporary work directory. But because in the
buildserver we have 'rm_work' enabled to save space, sometimes the
rm-work class has removed the 'qtbase' work directory before
'qtdeclarative' has been built, leading to the compilation error.

This is probably a bug in 'meta-qt5', because the different packages
needing QT5 base libraries should take them at compile time from the
sysroot and not from the qtbase work directory.

At the moment just workaround this adding an exception to the rm-work
class to not remove the 'qtbase' temporary work directory.

Signed-off-by: Javier Viguera <javier.viguera@digi.com>