meta-digi: delete outdated opencv bbappend
A new set of meta-freescale updates broke our layer, because they
updated opencv package and our bbappend does not apply anymore.

The build fails at parsing:

ERROR: No recipes in default available for:
  meta-digi/meta-digi-dey/dynamic-layers/freescale-layer/recipes-support/opencv/opencv_4.5.2.imx.bbappend

Signed-off-by: Javier Viguera <javier.viguera@digi.com>