weston: remove deprecated recipe
meta-freescale updated to version '10.0.0.imx', so our bbappend fails
with:

ERROR: No recipes in default available for:
  ... meta-digi-dey/dynamic-layers/freescale-layer/recipes-graphics/wayland/weston_9.0.0.imx.bbappend

Signed-off-by: Javier Viguera <javier.viguera@digi.com>