gst-plugins-base: fix warning (ivorbis conflict)
Disable integer vorbis plugin as it conflicts with other vorbis
plugins. Error:

error: GLib-GObject-WARNING **: cannot register existing type `GstVorbisDec'

Signed-off-by: Javier Viguera <javier.viguera@digi.com>