firmware-imx: make bbappend version agnostic
meta-freescale updated the base recipe and that broke the build:

ERROR: No recipes in default available for:
  meta-digi-arm/dynamic-layers/freescale-layer/recipes-bsp/firmware-imx/firmware-imx_8.16.bbappend

The differences in our bbappend are simple enough that we can make a
version agnostic bbappend.

Signed-off-by: Javier Viguera <javier.viguera@digi.com>