gst-plugins-good: remove 'x11' dependency for minimal image (no-X)
Fix error:

ERROR: Required build target 'del-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['del-image-minimal', 'packagegroup-del-gstreamer', 'gst-plugins-good', 'gconf', 'polkit', 'consolekit', 'virtual/libx11']

Signed-off-by: Javier Viguera <javier.viguera@digi.com>