build.sh: generate tarballs from git repositories
This is needed when you use a PREMIRROR (as we usually do in buildserver
builds). Otherwise there is a strange corner case where the do_fetch
task fails when the upstream git repo has been rebased and the old mirror
tarball does not have the new SHA1 revision.

ERROR: Function failed: Fetcher failure for URL: 'git://git.yoctoproject.org/matchbox-window-manager'. Unable to fetch URL from any source.

Signed-off-by: Javier Viguera <javier.viguera@digi.com>