recipes-graphics: imx-gpu-viv: Update recipes to new BSP release imx_5.4.47_2.2.0
Includes:
imx-gpu-viv-6.inc: Update files in libopencl-imx package

    Fix issue:
    ERROR: imx-dpu-g2d-1.8.9-r0 do_package_qa: QA Issue: /usr/lib/libg2d-dpu.so
    contained in package imx-dpu-g2d requires libOpenCL.so.1()(64bit), but no
    providers found in RDEPENDS_imx-dpu-g2d? [file-rdeps]

    Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>
imx-gpu-viv: Update library installation

    The packaging model has been reworked so now we can simply
    copy the libraries.

    Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
imx-gpu-viv: Integrate recipe updates

    Integrate our local recipe updates into the
    copied include file.

    Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
imx-gpu-viv: Copy include file from meta-freescale

    Changes are extensive enough now that it makes sense to
    simply copy what is upstream.

    Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>

kernel-module-imx-gpu-viv: Switch branch to imx_5.4.47_2.2.0

    Signed-off-by: i.MX Yocto Project Build <imx.build@nxp.com>
imx-gpu-viv: remove wayland as a requirement for i.MX8 platforms

    Based on commit ed2c4974 ("imx-gpu-viv: remove wayland as a requirement for
    i.MX8 platforms"), this commit removes the requeriment of wayland as a backend
    for the i.MX8 platforms to build framebuffer images.

    https://jira.digi.com/browse/DEL-7013

    Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>

imx-gpu-viv-v6: remove kernel-module-imx-gpu-viv dependency

    This dependency was originally removed in commit
    eafa8684a3ccdbad39a3fcf8cf0b6d6d79d11c5c, but it was erroneously put back in
    commit 793e901678bb68f289a951be1d2e1a0f7d8face9 when updating the recipe using
    the one in meta-fsl-bsp-release as reference.

    Instead of removing the line containing the dependency, in order to avoid the
    same situation from happening in the future,  comment it out and add an
    explanation about why we're removing it.

    Signed-off-by: Gabriel Valcazar <gabriel.valcazar@digi.com>

Signed-off-by: Hector Bujanda <Hector.Bujanda@digi.com>