base-files: fix bitbake parsing error
An error appeared trying to setup a jenkins job to build yocto.

When using dettached repos for the different layers (as a result of
using 'repo' tool) bitbake somehow fails to parse 'base-files' recipe
because the branch of the layers is '(no branch)'.

The error message is:

ERROR: ExpansionError during parsing /data/jenkins/jobs/yocto_test/workspace/digi-yocto-sdk.jviguera_mkproject/sources/poky/meta/recipes-core/base-files/base-files_3.0.14.bb: Failure expanding variable do_install: ShellSyntaxError: LexToken(TOKEN,'nobranch',0,0)
followed by:
  LexToken(RPARENS,')',0,0)
  LexToken(TOKEN,':34e5537e67b655b8d2effbbecc207d88eea52b87"\nmeta-fsl-arm      = "',0,0)
  LexToken(LPARENS,'(',0,0)
  LexToken(TOKEN,'nobranch',0,0)
  LexToken(RPARENS,')',0,0)

This commit fixes the problem.

Signed-off-by: Javier Viguera <javier.viguera@digi.com>